"""
Rime 词库文件解析器与生成器
支持解析与导出 Rime *.userdb.txt 及 custom_phrase.txt 格式
"""

import os
import re
from dataclasses import dataclass, field
from typing import Dict, List, Tuple, Optional

@dataclass
class UserDbEntry:
    word: str
    code: str
    weight: float = 1.0
    commit_count: int = 1
    raw_meta: str = ""
    last_commit_time: int = 0
    extra: Dict[str, str] = field(default_factory=dict)

    def to_userdb_line(self) -> str:
        """导出为 userdb.txt 格式行"""
        if self.raw_meta:
            # 保持或构造元数据描述，如 c=5 d=0.8 t=17000000
            meta = self.raw_meta
        else:
            meta = f"c={self.commit_count} d={self.weight:.4f}"
            if self.last_commit_time > 0:
                meta += f" t={self.last_commit_time}"
        return f"{self.word}\t{self.code}\t{meta}"

    def to_custom_phrase_line(self) -> str:
        """导出为 custom_phrase.txt 格式行"""
        return f"{self.word}\t{self.code}\t{int(self.weight)}"


class RimeParser:
    @staticmethod
    def parse_file(filepath: str) -> Tuple[List[str], Dict[Tuple[str, str], UserDbEntry]]:
        """
        解析 Rime userdb 或 custom_phrase 文本文件
        返回: (header_lines, entries_dict)
        entries_dict 的 key 为 (word, code)
        """
        headers = []
        entries: Dict[Tuple[str, str], UserDbEntry] = {}

        if not os.path.exists(filepath):
            return headers, entries

        with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                line_str = line.strip("\r\n")
                if not line_str:
                    continue

                if line_str.startswith("#"):
                    headers.append(line_str)
                    continue

                parts = line_str.split("\t")
                if len(parts) < 2:
                    continue

                word = parts[0].strip()
                code = parts[1].strip()

                if not word or not code:
                    continue

                weight = 1.0
                commit_count = 1
                last_time = 0
                raw_meta = ""

                if len(parts) >= 3:
                    raw_meta = parts[2].strip()
                    # 尝试解析 c=xx d=xx t=xx 格式
                    c_match = re.search(r'c=(\d+)', raw_meta)
                    d_match = re.search(r'd=([\d.]+)', raw_meta)
                    t_match = re.search(r't=(\d+)', raw_meta)

                    if c_match:
                        commit_count = int(c_match.group(1))
                        weight = float(commit_count)
                    if d_match:
                        weight = float(d_match.group(1))
                    if t_match:
                        last_time = int(t_match.group(1))

                    if not c_match and not d_match:
                        # 纯数字格式
                        try:
                            weight = float(raw_meta)
                            commit_count = int(weight)
                        except ValueError:
                            weight = 1.0

                key = (word, code)
                entries[key] = UserDbEntry(
                    word=word,
                    code=code,
                    weight=weight,
                    commit_count=commit_count,
                    raw_meta=raw_meta,
                    last_commit_time=last_time
                )

        return headers, entries

    @staticmethod
    def dump_userdb(filepath: str, headers: List[str], entries: Dict[Tuple[str, str], UserDbEntry]) -> None:
        """导出为标准 Rime userdb.txt 文件"""
        os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as f:
            for h in headers:
                f.write(f"{h}\n")
            if not headers:
                f.write("# Rime user dictionary database dump\n")

            for entry in entries.values():
                f.write(f"{entry.to_userdb_line()}\n")

    @staticmethod
    def dump_custom_phrase(filepath: str, entries: Dict[Tuple[str, str], UserDbEntry]) -> None:
        """导出为 custom_phrase.txt 文件"""
        os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write("# Rime custom phrase database (generated by rime-aisync)\n")
            for entry in entries.values():
                f.write(f"{entry.to_custom_phrase_line()}\n")
